---
- block:

  - name: Check if Nessus CLI file exists
    stat: 
      path: /opt/nessus/sbin/nessuscli
    register: nessus_cli

  - name: Download latest version of Nessus
    ansible.builtin.get_url:
      force: true
      url: https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-latest-ubuntu1604_amd64.deb
      dest: /tmp/Nessus-latest-ubuntu1604_amd64.deb

  - name: Install Nessus
    become: true
    ansible.builtin.command: dpkg -i /tmp/Nessus-latest-ubuntu1604_amd64.deb
    when: not nessus_cli.stat.exists

  - name: Start Nessus service
    become: true
    ansible.builtin.command: systemctl start nessusd.service

  - name: Set web server to listen on localhost only
    become: true
    ansible.builtin.command: /opt/nessus/sbin/nessuscli fix --set listen_address=127.0.0.1
    when: not nessus_cli.stat.exists

  - name: Disable scan vulnerability groups
    become: true
    ansible.builtin.command: /opt/nessus/sbin/nessuscli fix --set scan_vulnerability_groups=no
    when: not nessus_cli.stat.exists

  - name: Disable scan vulnerability groups mixe
    become: true
    ansible.builtin.command: /opt/nessus/sbin/nessuscli fix --set scan_vulnerability_groups_mixed=no
    when: not nessus_cli.stat.exists

  - name: Remove Nessus deb file
    ansible.builtin.file:
      path: /tmp/Nessus-latest-ubuntu1604_amd64.deb
      state: absent
    when: not nessus_cli.stat.exists

  tags:
    - Nessus