---
- block:

  - name: Install common apt packages and dependencies
    become: true
    ansible.builtin.apt:
      update_cache: yes
      state: present
      name:
        - build-essential
        - software-properties-common       
        - python3
        - python3-pip
        - python3-setuptools
        - python3-venv
        - python3-dev
        - python3-wheel
        - virtualenv
        - libpq-dev
        - dkms
        - chromium
        - code-oss
        - firefox-developer-edition-en-us-kbx
        - git
        - golang
        - jq

  - name: Set apt repositories cache as updated
    set_fact:
      apt_cached_updated: yes

  tags:
    - common-apt
